os: osx
osx_image: xcode12
language: objective-c
script:
    - xcodebuild -project "libAVPlayerJava XCode Project/AVPlayerJava.xcodeproj" -list
    - xcodebuild clean build -project "libAVPlayerJava XCode Project/AVPlayerJava.xcodeproj" -configuration Release
